### PR TITLE
added ability to pass --xvfb-run-args which are pushed down to Xvfb when present else stripped otherwise

### PR DESCRIPTION
**Pull request by uuf6429**
@brian-mann if your changes work (I haven't tried it yet), why not push changes to upstream?
@paulcbetts what do you think?

(disclaimer: I'm pushing for these changes since I need them as well 😄)

### CODE REVIEW

**Comment by brian-mann** [comment]
It works. We're using it at cypress.

**Comment by anaisbetts** [comment]
I'd rather use the UNIX standard `--` here, so, if you see `--` in the args, everything to the left of the args is forwarded to xvfb-run, and everything to the right of the args is sent to the target. For example:

```sh
# No --, everything goes to target
xvfb-maybe echo "foo"
```

```sh
# --foo goes to xvfb-run, 'ls -l .' is the command
xvfb-maybe --foo -- ls -l .
```

**Comment by uuf6429** [comment]
No complaints from my side.... who's doing it? ;)

I can give it a try, but I suppose I'll have to have another PR (and close this one).

**Comment by anaisbetts** [comment]
@uuf6429 Just keep committing to this one, no need to create a new PR

**Comment by uuf6429** [comment]
I don't think I can, the PR points to Brian's fork (and I'm not allowed to change the PR base).

**Comment by uuf6429** [comment]
Implemented in #5 (@brian-mann I urge you to also give it a look)

**Comment by uuf6429** [comment]
Implemented in #5 (@brian-mann I urge you to also give it a look)

**Pull request closed without merging**
