### PR TITLE
Added support for xvfb-run arguments

### LINKED ISSUE #3: Should be possible to specify options to xvfb-run
Maybe add support for something like this:

`xvfb-maybe -a -- <the command to run "in" xvfb-run>`

On a headless Linux box, this would expand to:

`xvfb-run -a <the command to run>`

While on a OS X box it would become:

`<the command to run>`

### PR DESCRIPTION
**Pull request by uuf6429**
## Tests
```javascript
let args = ['myapp', '-vvv', '--env=test'];
const dblDashPos = args.indexOf('--'),                             // -1
  xvfbArgs = dblDashPos === -1 ? [] : args.splice(0, dblDashPos),  // []
  exeCmd = dblDashPos === -1 ? args[dblDashPos === -1 ? 0 : 1],    // 'myapp'
  exeArgs = args.splice(dblDashPos === -1 ? 1 : 2);                // ['-vvv', '--env=test']
```
```javascript
let args = ['-a', '--', 'myapp', '-vvv', '--env=test'];
const dblDashPos = args.indexOf('--'),                             // 1
  xvfbArgs = dblDashPos === -1 ? [] : args.splice(0, dblDashPos),  // ['-a']
  exeCmd = dblDashPos === -1 ? args[dblDashPos === -1 ? 0 : 1],    // 'myapp'
  exeArgs = args.splice(dblDashPos === -1 ? 1 : 2);                // ['-vvv', '--env=test']
```

## Notes
- When not run through `xvfb-run`, the `xvfbArgs` variable is rightfully unused.
- This PR also fixes #3.
- This PR will change the behaviour of how double dashes were previously handled (or the fact that they were ignored):
    ```shell
    # Before:
    xvfb-maybe prog arg1 -- arg2       => prog arg1 -- arg2
    # Now:
    xvfb-maybe prog arg1 -- arg2       => arg1 arg2
    # Fix:
    xvfb-maybe -- prog arg1 -- arg2    => prog arg1 -- arg2
    ```

### CODE REVIEW

**Comment by SDohle** [comment]
When will this PR merged?

**Comment by anaisbetts** [comment]
@uuf6429 Thanks!

**Comment by anaisbetts** [comment]
This is xvfb-maybe 0.2.0

**Comment by jjgonecrypto** [comment]
Unfortunately this PR just added CRLF line endings to the binary, meaning that in POSIX environments you now see `env: node\r: No such file or directory`

**Comment by uuf6429** [comment]
I've just noticed it a few moments ago, couldn't figure out the reason. :(

**Comment by uuf6429** [comment]
The problem seems to be inside the package downloaded by npm:
- if you clone the repo, everything is fine
- if create a new npm project and install `xvfb-maybe`, some downloaded files have their EOL messed up

I've never packaged npm myself, so I don't know how it's done. Maybe @paulcbetts knows more about the situation?

**Edit:** Yep, seems to be a common package issue: https://github.com/npm/npm/issues/2097

**Comment by SDohle** [comment]
Got the `env: node\r: No such file or directory` too (linux)

**Comment by jjgonecrypto** [comment]
Seems as though this is the best workaround https://github.com/npm/npm/issues/12371#issuecomment-293211866

**Comment by anaisbetts** [comment]
@uuf6429 @SDohle This should be fixed in 0.2.1, sorry. c9a9e8917c7d is the lazy fix

**Pull request merged**
